enable-magisk-update = true 
parallel-jobs = 1

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[GooglePhotos]
build-mode = "both"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[Music-Extended]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Twitter]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"

[TikTok]
enabled = false
included-patches = "'SIM spoof'"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

######################################################################################################################################################################

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
included-patches = "'Hide ads' 'Sanitize sharing links' 'Disable signature check'"
exclusive-patches = true

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Lightroom]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"

[MemeGenerator]
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"

[NetGuard]
apkmirror-dlurl = "https://www.apkmirror.com/apk/marcel-bokhorst/netguard-no-root-firewall/"

[ORFON]
apkmirror-dlurl = "https://www.apkmirror.com/apk/orf-osterreichischer-rundfunk/orf-tvthek-video-on-demand/"

[Pandora]
apkmirror-dlurl = "https://www.apkmirror.com/apk/pandora/pandora-music-podcasts/"

[Photomath]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"

[pixiv]
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"

[ProtonMail]
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email/"

[RAR]
apkmirror-dlurl = "https://www.apkmirror.com/apk/rarlab-published-by-win-rar-gmbh/rar/"

[BaconReader]
apkmirror-dlurl = "https://www.apkmirror.com/apk/onelouder-apps/baconreader-for-reddit/"

[InfinityForRedditPatreon]
apkmirror-dlurl = "https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit-patreon-github-version/"

[InfinityForRedditPlus]
apkmirror-dlurl = "https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit-plus/"

[RIFForReddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/talklittle/reddit-is-fun/"

[RelayForReddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/dbrady/relay-for-reddit-2/"

[SlideForReddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/haptic-apps/slide-for-reddit/"

[SyncForLemmy]
apkmirror-dlurl = "https://www.apkmirror.com/apk/sync-apps-ltd/sync-for-lemmy/"

[SamsungRadio]
apkmirror-dlurl = "https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/"

[SolidExplorer]
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-beta/"

[SonySoundConnect]
apkmirror-dlurl = "https://www.apkmirror.com/apk/sony-corporation/sony-headphones-connect/"

[SoundCloud]
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"

[Stocard]
apkmirror-dlurl = "https://www.apkmirror.com/apk/stocard-gmbh/stocard-rewards-cards-wallet/"

[Strava]
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-run-bike-hike-2/"

[Threads]
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app/"

[TickTick]
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/ticktick-to-do-list-with-reminder-day-planner/"

[Trakt]
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/trakt/"

[Tumblr]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tumblr-inc/tumblr/"

[Viber]
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/viber/"

[WarnWetter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Willhaben]
apkmirror-dlurl = "https://www.apkmirror.com/apk/willhaben/willhaben/"
